### ISSUE TITLE
Not able to create more than 500 version from a account.

### ISSUE THREAD

**Issue by somit** [hashedin/django-project-template#5]
"_get_response
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
{"Error":{"Code":"TooManyApplicationVersionsException","Message":"You cannot have more than 500 Application Versions. Either remove some Application Versions or request a limit increase.","Type":"Sender"},"RequestId":"c50a1903-a9d8-11e3-88af-fffac8f44669"}
Build step 'Execute shell' marked build as failure

**Comment by mishrav** [comment]
eb labs cleanup-versions --help
usage: eb labs cleanup-versions [options...]

Cleans up old application versions.

optional arguments:
--num-to-leave NUM    number of versions to leave DEFAULT=10
--older-than DAYS     delete only versions older than x days DEFAULT=60
--force               don't prompt for confirmation
